# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raspberry Pi
email: e.yllanescucho@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Bienvenidos!</h3><h1>Curso de Raspberry Pi</h1>"



baseurl: "" # the subpath of your site, e.g. /blog
url: # http://hemangsk.github.io" # the base hostname & protocol for your site
twitter_username: eyllanesc
github_username:  eyllanesc

# Build settings
markdown: kramdown

plugins: [jekyll-gist]
